### ISSUE TITLE
Very first userstory

### ISSUE THREAD

**Issue by magu1216** [magu1216/wespawn_project#1]
### Value Statement

As a gamer
I want to set my own profile with my username and profile picture
so that I can demonstrate myself with played platforms and uploads.

### Description

- User have got a profile with username and picture
- There are categories for platforms and uploaded contents
- One can use buttons for quick actions

![Untitled-2020-11-16-1549(3)](https://user-images.githubusercontent.com/61665279/99405549-2fd85900-28ed-11eb-858e-306bae2299ab.png)

### Acceptance criteria

- [ ] User can set q "looking for group"-Status, button and picture icon change when set

- [ ] User can upload images and videos and store it in the profile page

- [ ] Other users can be added to a friendlist

- [ ] With a burger menu users can see more functions and settings

### Tasks

- [ ] Create feature branch

- [ ] Set up the technical core of the app

- [ ] Build components like buttons, header and footer
